spring.application.name=PlantCare

spring.database.url = jdbc:mysql://localhost:3306/plantcare
spring.database.username = root
spring.database.password = prabhat


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true